# Generated by Django 4.2.4 on 2023-08-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResistanceExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("picture", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyTrainingVolumeWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wknr", models.IntegerField(null=True)),
                ("exercise", models.CharField(max_length=100)),
                ("total_exercise_weight_volume", models.IntegerField()),
                ("intensity_zone_1", models.IntegerField()),
                ("intensity_zone_2", models.IntegerField()),
                ("intensity_zone_3", models.IntegerField()),
                ("intensity_zone_4", models.IntegerField()),
                ("intensity_zone_5", models.IntegerField()),
                ("intensity_zone_6", models.IntegerField()),
                ("intensity_zone_7", models.IntegerField()),
                ("intensity_zone_8", models.IntegerField()),
                ("intensity_zone_9", models.IntegerField()),
                ("intensity_zone_10", models.IntegerField()),
                ("intensity_zone_11", models.IntegerField()),
                ("intensity_zone_12", models.IntegerField()),
                ("intensity_zone_13", models.IntegerField()),
                ("week", models.IntegerField()),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyTrainingVolum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wknr", models.IntegerField(null=True)),
                ("exercise", models.CharField(max_length=100)),
                ("total_intensity_zone", models.IntegerField()),
                ("intensity_zone_1", models.IntegerField()),
                ("intensity_zone_2", models.IntegerField()),
                ("intensity_zone_3", models.IntegerField()),
                ("intensity_zone_4", models.IntegerField()),
                ("intensity_zone_5", models.IntegerField()),
                ("intensity_zone_6", models.IntegerField()),
                ("intensity_zone_7", models.IntegerField()),
                ("intensity_zone_8", models.IntegerField()),
                ("intensity_zone_9", models.IntegerField()),
                ("intensity_zone_10", models.IntegerField()),
                ("intensity_zone_11", models.IntegerField()),
                ("intensity_zone_12", models.IntegerField()),
                ("intensity_zone_13", models.IntegerField()),
                ("week", models.IntegerField()),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingRepMax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise", models.CharField(max_length=100)),
                ("rm_value", models.IntegerField()),
                ("pr_date", models.DateField()),
                ("reps", models.IntegerField(null=True)),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resistanceexercise",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trening_db.student"
            ),
        ),
        migrations.CreateModel(
            name="DailyVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("weight", models.IntegerField()),
                ("injury_status", models.BooleanField()),
                ("injury_type", models.CharField(max_length=100)),
                ("sleep_quality", models.IntegerField()),
                ("sleep_duration", models.IntegerField()),
                ("rpe", models.IntegerField()),
                ("prs", models.IntegerField()),
                ("training_period", models.CharField(max_length=100)),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTrainingVolumeWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("day", models.CharField(max_length=100)),
                ("exercise", models.CharField(max_length=100)),
                ("total_exercise_weight_volume", models.IntegerField()),
                ("intensity_zone_1", models.IntegerField()),
                ("intensity_zone_2", models.IntegerField()),
                ("intensity_zone_3", models.IntegerField()),
                ("intensity_zone_4", models.IntegerField()),
                ("intensity_zone_5", models.IntegerField()),
                ("intensity_zone_6", models.IntegerField()),
                ("intensity_zone_7", models.IntegerField()),
                ("intensity_zone_8", models.IntegerField()),
                ("intensity_zone_9", models.IntegerField()),
                ("intensity_zone_10", models.IntegerField()),
                ("intensity_zone_11", models.IntegerField()),
                ("intensity_zone_12", models.IntegerField()),
                ("intensity_zone_13", models.IntegerField()),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTrainingVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("day", models.CharField(max_length=100)),
                ("exercise", models.CharField(max_length=100)),
                ("total_exercise_reps_volume", models.IntegerField()),
                ("intensity_zone_1", models.IntegerField()),
                ("intensity_zone_2", models.IntegerField()),
                ("intensity_zone_3", models.IntegerField()),
                ("intensity_zone_4", models.IntegerField()),
                ("intensity_zone_5", models.IntegerField()),
                ("intensity_zone_6", models.IntegerField()),
                ("intensity_zone_7", models.IntegerField()),
                ("intensity_zone_8", models.IntegerField()),
                ("intensity_zone_9", models.IntegerField()),
                ("intensity_zone_10", models.IntegerField()),
                ("intensity_zone_11", models.IntegerField()),
                ("intensity_zone_12", models.IntegerField()),
                ("intensity_zone_13", models.IntegerField()),
                (
                    "mode_of_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
    ]
