# Generated by Django 4.2.4 on 2023-08-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trening_db", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyVariables",
        ),
    ]
