# Generated by Django 4.2.4 on 2023-08-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trening_db", "0002_delete_dailyvariables"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvulationRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ovulation_situation", models.BooleanField(default=False)),
                (
                    "ovulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
    ]
