# Generated by Django 4.2.4 on 2023-08-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trening_db", "0003_ovulationregistry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ovulationregistry",
            name="day",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name="MenstruationRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day", models.CharField(max_length=100)),
                ("menstruation_situation", models.CharField(max_length=100)),
                ("numerical_menstruation_situation", models.IntegerField()),
                (
                    "menstruation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trening_db.resistanceexercise",
                    ),
                ),
            ],
        ),
    ]
